---
collections:
  - name: redhat.rhel_system_roles
  - name: redhat.runtimes_common
  - name: redhat.eap
  - name: redhat.openshift_virtualization
  - name: redhat.openshift
  - name: openstack.cloud
