---
- name: Create a namespace
  redhat.openshift.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create a VirtualMachine
  redhat.openshift_virtualization.kubevirt_vm:
    state: present
    name: "{{ item.name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ label_app }}"
    instancetype:
      name: "{{ instance_type }}"
    preference:
      name: "{{ preference_name }}"
    data_volume_templates:
      - metadata:
          name: "{{ item.name }}-volume"
        spec:
          sourceRef:
            kind: DataSource
            name: "{{ rhel_machine }}"
            namespace: openshift-virtualization-os-images
          storage:
            resources:
              requests: {}
    spec:
      domain:
        devices:
          interfaces:
            - bridge: {}
              model: virtio
              name: default
        machine:
          type: "{{ machine_type }}"
        resources: {}
      networks:
        - multus:
            networkName: "{{ network_name }}"
          name: default
      volumes:
        - dataVolume:
            name: "{{ item.name }}-volume"
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              debug: True
              ssh_pwauth: True
              disable_root: false
              PermitRootLogin: Yes
              X11Forwarding: yes
              chpasswd:
                expire: false
              password: 123qwe
              user: root
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv7hj0tKRyOIr22gcWK8ik/Wtgn39VdkUGjfedKqaZjRRO/rIy+sL4vgi1DkhUmmqkbqwiklGGmqebZmTC+LEgT74P2wZa5Pk3dG+Imyxg536PNB1nGHro+WlbsROCTOeMH3/5R7dQWpwNZtep8PE/bKoLSCxiT0eoLeM3GPQhZDzs40OWK3JshFfaW5iHO+EjncjWKGhzfVr5Jjg09fu6ARt9LS3G0N2kbnvEVP3c0nw+o073caCDkQ71WAoxS62POpJT5u+YmwDJZ+RIQYSa36H02/RTNFf8jW0BUnxvVHl26pbc/UxJmJb4GcCQ9pXGbekwHI+ksjzf2WHI6J8z Generated-by-Nova
          name: cloudinit
    wait: true
  loop: "{{ vm }}"