# oc apply -f kube-network-attachment.yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: "l2 connection for vms"
  name: vlan0
  namespace: devconf-demo
spec:
  config: '{"name":"vm-network","type":"ovn-k8s-cni-overlay","cniVersion":"0.4.0","topology":"localnet","netAttachDefName":"devconf-demo/vlan0"}'