---
- name: launch an instance
  openstack.cloud.server:
    state: "{{ state }}"
    auth_type: "{{ auth_type }}"
    auth:
      auth_url: "{{ auth_url }}"
      project_domain_id: "{{ project_domain_id }}"
      application_credential_id: "{{ application_credential_id }}"
      application_credential_secret: "{{ application_credential_secret }}"
    region_name: "{{ region_name }}"
    interface: "public"
    name: "{{ item.name }}"
    availability_zone: "{{ availability_zone }}"
    image: "{{ image }}"
    boot_from_volume: "{{ boot_from_volume }}"
    volume_size: "{{ volume_size }}"
    flavor: "{{ flavor }}"
    key_name: "{{ key_name }}"
    terminate_volume: "{{ terminate_volumes }}"
    network: "{{ network }}"
    meta:
      hostname: "{{ item.name }}"
      group: "{{ group }}"
    userdata: |
      #cloud-config
      debug: true
      ssh_pwauth: true
      disable_root: false
      chpasswd:
        list: |
          root:123qwe
          cloud-user:123qwe
        expire: false
  loop: "{{ vm }}"
  register: instances