---
- name: Remove OpenStack instance
  openstack.cloud.server:
    auth_type: "{{ auth_type }}"
    auth:
      auth_url: "{{ auth_url }}"
      project_domain_id: "{{ project_domain_id }}"
      application_credential_id: "{{ application_credential_id }}"
      application_credential_secret: "{{ application_credential_secret }}"
    region_name: "{{ region_name }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ vm }}"
