---
- name: Remove OpenStack instance
  openstack.cloud.server:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_id: "{{ project_id }}"
      user_domain_name: "{{ user_domain_name }}"
    region_name: "{{ region_name }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ vm }}"
